### ISSUE TITLE
regiment data is not take into account?

### ISSUE THREAD

**Issue by benphil** [ronkeizer/PKPDsim#10]
Dear Ron,
if I run the sim_ode_shiny I dont get the regiment (r3 below) filled in as the default values (e.g. amt=200). It seems to stay at 100 and also the infusion time is not changed. Do you have an idea how to fix it?

Best wishes,
Ben

Code:
p <- list(CL = 1, V  = 1)
r3 <- new_regimen(amt = 200,
                  times = c(0, 12, 24, 36),
                  type = "infusion", t_inf = 3)

pk_1cmt_iv <- function (t, A, p) {
  with(p, {
    KEL <-  CL/V
    dAdt_1 <- -KEL*A[1] + rate
    return ( list ( c (  dAdt_1 ) ) )
  })
}

omega <- c(0.4,       # IIV CL
           0.1, 0.3)  # IIV V
sim_ode_shiny(code = "dAdt[1] = -(CL/V)*A[1] ; ",
              par = p,
              regimen = r3,
              omega = omega,
              )

**Comment by dpastoor** [comment]
ben,

a guess is you actually aren't using the iv_infusion code you defined in `pk_1cmt_iv`, instead you are defining a iv-bolus style equation in the code. 

based on the [vignette](http://ronkeizer.github.io/PKPDsim/) example you should point the ode to your newly defined `pk_1cmt_iv`

```
dat <- sim_ode (ode = "pk_1cmt_iv",
                par = p,
                regimen = r3,
                omega=omega)
```

See if that works.

**Comment by benphil** [comment]
Dear dpastoor,
you are right, like that it is not using the newly created model. Sorry for this example. However, my issue is that the newly build shiny file ui.r has always fixed starting values due to e.g.
textInput("amt", "Amount:", value = "100")),
and these are not paste from 
regimen <- readRDS("regimen.rds")
as it is done in server.r

Therefore (I think) whatever you define as regiment is lost in the shiny app. 

Ben

**Comment by ronkeizer** [comment]
hi Ben, 
thanks for reporting. This happens because that part of the interface does not take the info from the input object yet, so every dose will default to 100 and interval of 12. Nothing wrong with your code. Will update a.s.a.p.

**Comment by benphil** [comment]
Thanks Ron!

Great project bye the way!

**Comment by ronkeizer** [comment]
should be fixed now.

**Comment by benphil** [comment]
Thanks Ron it now works. However I get some errors. Is that related to the changes you made?

Error in if (length(grep("CI", input$plot_type)) > 0 & input$n_ind < 10) { : 
  argument is of length zero
Error in if (length(grep("CI", input$plot_type)) > 0 & input$n_ind >=  : 
  argument is of length zero
Error in if (!(type %in% c("bolus", "oral", "infusion"))) { : 
  argument is of length zero
Error in if (!(type %in% c("bolus", "oral", "infusion"))) { : 
  argument is of length zero

**Comment by benphil** [comment]
Hi Ron,
any chance to look into these issues?

Thanks,
Ben

**Comment by ronkeizer** [comment]
sorry, haven't had time to look at the Shiny part, focused mostly on the simulation engine lately. Will try to have a look later this week. 
FYI, the Shiny part will also be split off in a separate module soon.
