### ISSUE TITLE
Shiny problem model loading

### ISSUE THREAD

**Issue by benphil** [ronkeizer/PKPDsim#11]
When using a new model defined in the code as shown below the shiny app needs the model to be in the workspace which on a shiny server is not the case and that creates the error "new_model not found". 

sim_ode_shiny(ode = "new_model",
              par = p,
              regimen = r1)

**Comment by ronkeizer** [comment]
can you provide the complete code?

**Comment by benphil** [comment]
#Antibody PK model
antibody_pk_model <- new_ode_model(
  code = "
  dAdt[1] = -(CL/V)_A[1] - (Q/V)_A[1] + (Q/V2)_A[2] + rate;
  dAdt[2] = -(Q/V2)_A[2] + (Q/V)*A[1];
  conc = A[1]/V;
  ",
  obs=list(cmt = 1, scale = "V"),
  dose = list(cmt = 1),
  size = 2
)

#Dosing
r1 <- new_regimen(amt = 200,
                  times = c(0, 12, 24, 36),
                  type = "infusion"
)

#Parameters
p <- list(CL = 2, V  = 50, Q = 70, V2 = 100)

#Make Shiny
sim_ode_shiny(ode = "antibody_pk_model",
              par = p,
              regimen = r1)

if you then do 
rm(antibody_pk_model)
and 
runApp(shiny_folder)
it does not work out with the model file in the misc.rds.

Thanks,
Ben

**Comment by ronkeizer** [comment]
ah, I understand now what you're trying to do. No, that indeed will not work. For now, you will need to edit the generated server file (server.R) manually and put the model definition in there. In a next iteration I will allow the user to include the model definition automatically, so you can run the Shiny server independently.

**Comment by benphil** [comment]
Hi Ron,
Thanks for your reply. I tried that as well could you maybe send me an example how to do that in the server.r?

Best wishes,
Ben

**Comment by ronkeizer** [comment]
in the file ~/shiny-pkpd/server.R, replace the following

```
if(!is.null(misc$code)) {
  model <- PKPDsim::new_ode_model (code = misc$code, obs = misc$obs)
} else {
  model <- misc$ode 
}
```

with 

```
model <- new_ode_model( <your model def here> )
```

that should work I think.

**Comment by Karamcse** [comment]
Hi Ronkeizerr,

I replaced your code as you given. How do I customize below function? 
model <- new_ode_model( <your model def here> )

I am getting below error. 

Stack trace (innermost first):
    40: sourceCpp
    39: compile_sim_cpp
    38: PKPDsim::new_ode_model
     1: shiny::runApp
Error in sourceCpp(code = sim_func, rebuild = TRUE, env = globalenv(),  : 
  Error 1 occurred building shared library.

**Comment by ronkeizer** [comment]
This code works for me (make sure you have the latest versions of the libraries from GitHub):

```
library(PKPDsim)
library(PKPDsimShiny)

antibody_pk_model <- new_ode_model(
  code = "
  dAdt[1] = -(CL/V)*A[1] - (Q/V)*A[1] + (Q/V2)*A[2] + rate;
  dAdt[2] = -(Q/V2)*A[2] + (Q/V)*A[1];
  conc = A[1]/V;
  ",
  obs=list(cmt = 1, scale = "V"),
  dose = list(cmt = 1),
  size = 2
)

#Dosing
r1 <- new_regimen(amt = 200,
                  times = c(0, 12, 24, 36),
                  type = "infusion"
)

#Parameters
p <- list(CL = 2, V = 50, Q = 70, V2 = 100)

#Make Shiny
sim_ode_shiny(ode = "antibody_pk_model",
              par = p,
              omega = c(0.1, 
                        0.05, 0.1),
              regimen = r1)
```

**Comment by Karamcse** [comment]
I installed latest version from github. But when I run above code. It is showing below error:
Loading required package: shiny

Attaching package: ‘shiny’

The following object is masked from ‘package:jsonlite’:

```
validate
```

Listening on http://127.0.0.1:4478

Attaching package: ‘deSolve’

The following object is masked from ‘package:graphics’:

```
matplot
```

Warning: Error in ..stacktraceon..: could not find function "error"
Stack trace (innermost first):
    2: shiny::runApp
    1: sim_ode_shiny
Error in ..stacktraceon..({ : could not find function "error"

**Comment by ronkeizer** [comment]
I do see this same error now on my other computer. I'm not sure why this occurs, perhaps a recent version of Shiny broke the way PKPDsimShiny interacted with it. At the moment I don't have time to look in to this. So for now, I would advise to create the Shiny app yourself, using PKPDsim as the simulation engine.
