### ISSUE TITLE
new_ode_model unaffected by dose argument

### ISSUE THREAD

**Issue by philipdelff** [ronkeizer/PKPDsim#12]
First of all, thank you very much for this great package!

Doses seem only to be given to the first compartment. The dose argument seems to have no effect on new_ode_model. The obs argument works as expected, incl. scaling. Example attached.

I often dose to multiple compartments in one simulation run. For this purpose, new_regimen would have to take cmt as argument. 

new_regimen_from_nm_dataset does not seem to use the CMT column in data either.

With the theflexibility on cmt, PKPDsim would be a very important tool for me. So thanks again.
- John

[sessionInfo_execresults.txt](https://github.com/ronkeizer/PKPDsim/files/211524/sessionInfo_execresults.txt)
[dose_cmt_debug_R.txt](https://github.com/ronkeizer/PKPDsim/files/211526/dose_cmt_debug_R.txt)
The plot is of new_ode_model(..., dose=list(cmt=2)).
![dosebug](https://cloud.githubusercontent.com/assets/5931516/14406960/81720c58-feb7-11e5-8e08-35dbb4d6440b.png)

**Comment by ronkeizer** [comment]
good catch, the compartment argument was indeed ignored and always set to
1. Should be fixed now, please install latest revision.

**Comment by philipdelff** [comment]
Thank you very much for the quick fix!
Best regards,
John
