### ISSUE TITLE
No possibility of dosing to multiple compartments

### ISSUE THREAD

**Issue by philipdelff** [ronkeizer/PKPDsim#13]
Hi,

I often need to dose into multiple compartments in one simulation run (due to either different formulations or split-depot models). For this purpose, cmt values would need to be part of regimens (at least, that's the way I see it). new_regimen would have to take cmt as argument.

new_regimen_from_nm_dataset does not seem to use the CMT column in data either.

Would it be possible to include this flexibility? It would be a huge help for my use of the library.

Best regards,
John

**Comment by ronkeizer** [comment]
hi John,
when implementing the previous fix regarding the compartment I already kept this in mind, and I put "flexible compartment input" on my to-do list. If I have some time I might implement it this week, otherwise probably next week.
br,
Ron

**Comment by philipdelff** [comment]
Hi Ron,
I don't want to stress you with this. But I'm happy that this feature is part of your plans. 
Best regards,
John

**Comment by ronkeizer** [comment]
you can now override the default dosing compartment using new_regimen(). E.g.:

```
reg1 <- new_regimen(amt=c(100,100,100), cmt=c(1,2,3), times=c(0,24,48))
```

will dose in compartments 1, 2, and 3 respectively.

**Comment by philipdelff** [comment]
Thank you! I'm working on a project these weeks where I will use this. Thanks for a great tool!
