### ISSUE TITLE
Library path gets stripped of some characters

### ISSUE THREAD

**Issue by cmollgaard** [ronkeizer/PKPDsim#16]
The path to my library looks something like this: "something/foldername$/morefolders/librarys". When running new_ode_model with the example in the tutorial i get the error, that it cannot find rccp.h.

After trying to debug i found that during the g++ call, the path to the the library gets converted to: "something/foldernamemorefolders/librarys" where the "$/" have been removed, so it cannot find the library.

I have not yet been able to locate just where the path is stripped of these characters yet.

This can locally be fixed by moving the library.

**Comment by ronkeizer** [comment]
The problem could be that the Boost C++ headers are not installed properly? can you try to install the library "BH" again (and also "Rcpp")? Not sure what is going on, but it actually seems more like a general issue with Rcpp than with PKPDsim.

**Comment by cmollgaard** [comment]
Closed as not an PKPDsim issue.
