### ISSUE TITLE
Simulation with a range of covariate values

### ISSUE THREAD

**Issue by bguiastr** [ronkeizer/PKPDsim#19]
Is there an easy way to have variability in the value of a covariate across different individuals? Either by specifying the distribution or provide a data.frame containing all covariates combination per ID?

**Comment by bguiastr** [comment]
Also if it is possible to recover the covariate values used for simulation in the output table?

**Comment by ronkeizer** [comment]
regarding q1: yes, initially had the plan to implement that (see e.g. the stub for the function in new_covariate_model.R). However, I've never really had the time or need to actually implement it in the package. Got this question recently from someone else too, so will bump it up on priority list :)

**Comment by ronkeizer** [comment]
regarding q2: not possible a.t.m. Is good idea though, so will add to list. (It's very easy to add this info for static covariates, somewhat more tricky for time-changing covariates).

**Comment by bguiastr** [comment]
Great ! Generally speaking I believe it could be valuable to output any model parameter or covariate in the table (i.e. in the spirit of NONMEM $TABLE). This makes sense especially for parameters with variability generated on the fly by the `sim()` function in combination with the `omega()` function.

**Comment by ronkeizer** [comment]
the above features are implemented. See arguments `covariate_table` and `include_output`. More info also in manual at pkpdsim.ronkeizer.com

**Comment by bguiastr** [comment]
Thank you very much for implementing these useful features! Maybe I am doing something wrong but I am experiencing some errors with:
- `output_include = list(parameters = TRUE, covariates = TRUE)` returns `Error in dat_ind[1, ] : subscript out of bounds` (see example 1 below for reproducible example)
- `covariates_table = cov_table` returns `Error in sim(ode = "model", par = prms, t_obs = c(0.5, 2, 4, 8, 12, 16,  : 
  Not all covariates for this model have been specified. Missing: 
  WT` (see example 2 below for reproducible example)

Example 1 (output_include covariates)

``` r
prms <- list(CL = 1, 
             V  = 10,
             KA = 0.5)

model <- new_ode_model(code = "
                       CLi = CL * pow((WT/70), 0.75)
                       Vi  = V * (WT/70)
                       dAdt[1] = -KA*A[1]
                       dAdt[2] =  KA*A[1] -(CLi/Vi)*A[2]
                       ", 
                       declare_variables = c('CLi', 'Vi'), 
                       covariates = c('WT'),
                       dose = list(cmt = 1), 
                       obs  = list(cmt = 2, scale = 'V * (WT/70)')
)

doses  <- new_regimen(amt = 30,
                      n   = 1,
                      type = 'bolus')

simtab <- sim(ode        = 'model',
              par        = prms,
              t_obs      = c(0.5, 2, 4, 8, 12, 16, 24),
              n_ind      = 10,
              regimen    = doses,
              covariates = list("WT" = new_covariate(value = 70)),
              output_include = list(parameters = TRUE, covariates = TRUE))
```

Example 2 (covariates table)

``` r
prms <- list(CL = 1, 
             V  = 10,
             KA = 0.5)

cov_table <- data.frame('id' = 1:10,
                        'WT' = rnorm(10, mean = 60, sd = 5))

model <- new_ode_model(code = "
                       CLi = CL * pow((WT/70), 0.75)
                       Vi  = V * (WT/70)
                       dAdt[1] = -KA*A[1]
                       dAdt[2] =  KA*A[1] -(CLi/Vi)*A[2]
                       ", 
                       declare_variables = c('CLi', 'Vi'), 
                       covariates = c('WT'),
                       dose = list(cmt = 1), 
                       obs  = list(cmt = 2, scale = 'V * (WT/70)')
)

doses  <- new_regimen(amt = 30,
                      n   = 1,
                      type = 'bolus')

simtab <- sim(ode        = 'model',
              par        = prms,
              t_obs      = c(0.5, 2, 4, 8, 12, 16, 24),
              n_ind      = 10,
              regimen    = doses,
              covariates_table = cov_table)
```

**Comment by ronkeizer** [comment]
thanks for checking Ben. indeed few small bugs. should be fixed now.
br,

**Comment by bguiastr** [comment]
Everything works perfectly now thanks!
