### ISSUE TITLE
NULL sim output when using a regimen from new_regimen_from_nm_dataset()

### ISSUE THREAD

**Issue by justinpenz** [ronkeizer/PKPDsim#20]
I am trying to simulate several dosing regimens simultaneously.  If I do not include t_obs as an argument in sim, I get 
`Error in round(t_obs, 8) : non-numeric argument to mathematical function` in the below code.
I've included obs_step_size and t_max, which work as expected, but without it (and with the t_obs arg), the step size defaults to 1 despite specification in t_obs.

Any idea whats going on? Below is the code which throws a funny result.
Thanks

p <- list(CL = 5, V  = 60)

pk1 <- new_ode_model(code =  
                    "
                    dAdt[1] = -CL/V \* A[1]
                    ",
                    obs = list(cmt = 1, scale = "V"))

NMdf <- rbind(expand.grid(TIME = seq(0,48,12), AMT = 1000, ID = 1, EVID = 1, rate = 10000),
              expand.grid(TIME = seq(0,48,6), AMT = 500, ID = 2, EVID = 1, rate = 10000),
              expand.grid(TIME = seq(0,48,6), AMT = 500, ID = 3, EVID = 1, rate = 500))

r5 <- new_regimen_from_nm_dataset(NMdf)

sim <- sim(ode = "pk1",
                parameters = p,
                regimen = r5,
                t_obs = seq(1,50, 0.1),
                obs_step_size = 0.1,
                t_max = 50,
                duplicate_t_obs = T,
                only_obs = T)

ggplot(sim, aes(x=t, y=y, group=id)) + geom_line() + facet_wrap(~id)

EDIT: delete duplicate code

**Comment by ronkeizer** [comment]
hi Justin,
thanks for reporing. There was indeed a parsing bug that caused wrong output times. Should be fixed now, please try again. Specifying only t_obs should be enough, no need for obs_step_size and/or t_max when t_obs is specified.

**Comment by justinpenz** [comment]
Works now. Thanks Ron!
