### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by benphil** [ronkeizer/PKPDsim#21]
Hi,
I have the following problem. After installing PKPDsim I try to simulate the first model using the code provided:

library(PKPDsim)

p <- list(CL = 1, V  = 10, KA = 0.5)
pk1 <- new_ode_model("pk_1cmt_oral")
r1 <- new_regimen(amt = 100,
                  n = 5,
                  interval = 12)
dat <- sim_ode (ode = "pk1",
                par = p,
                regimen = r1)

All steps go ok (it complains about 'bolus', 'oral', or 'infusion' but that is not a problem) but for the last one I get the following error code:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘DBI’ 0.3.1 is being loaded, but >= 0.4.1 is required

Any idea how I can fix this?

Thanks!

**Comment by ronkeizer** [comment]
not sure if this has anything to do with this package. Seems you need to update the DBI package? Have you tried that?

**Comment by benphil** [comment]
yes that was it, sorry for that. Bye the way, the compiling and simulation works really quick now. Great work!

**Comment by gracertliu** [comment]
Hi, 
I've same problem with Benphil, however, when I downloaded packages DBI and popgraph, there is no longer errors in the first model. Thank you.
