### ISSUE TITLE
Covariates: additional examples and error correction

### ISSUE THREAD

**Issue by bguiastr** [ronkeizer/PKPDsim#22]
A full model explaining how to simulate from a model with covariates in the model (i.e. declare names in the `new_ode_model`, set typical value or cov_table in `sim`) would be welcome in the documentation (in More Examples).

In addition, there are minor errors with the current examples under Model>More custom model options. In the example below the `declare_variables` should also include `CLi`.
```r
pk1 <- new_ode_model(code = "
  CLi = WT/70
  KEL = CLi/V
  dAdt[1] = -KA * A[1]
  dAdt[2] = +KA * A[1] -(CL*(WT/70)/V) * A[2]
", declare_variables = c("KEL", ""), covariates = c("WT"))
```

In the next example (see below) there is no need for `KEL` declaration.
```r
pk1 <- new_ode_model(code = "
  CLi = CL * pow((WT/70), 0.75)
  dAdt[1] = -KA * A[1]
  dAdt[2] = +KA * A[1] -(CLi/V) * A[2]
", declare_variables = c("KEL", "CLi"))
```

**Comment by ronkeizer** [comment]
fixed code + added example
