### ISSUE TITLE
Tutorial not updated

### ISSUE THREAD

**Issue by Sibojang9** [ronkeizer/PKPDsim#23]
Hi Ron,

When I tried to run the shiny examples, It says :" the sim_ode_shiny function is not available in the PKPDsim library anymore".  It is will be easy for learner if the tutorial keeps pace with the software. For example, to specify library(PKPDsimShiny) in the head of the tutorial.

Thank you,

Sibo

**Comment by ronkeizer** [comment]
thanks for the comment Sibo. Can I ask which tutorial you were referring too? In the Shiny section in the documentation the PKPDsimShiny library is included (http://pkpdsim.ronkeizer.com/example-shiny-app.html).

**Comment by Sibojang9** [comment]
Hi Ron,
I am referring to the Example Shiny at http://ronkeizer.github.io/PKPDsim/,  which is the very first tutorial my google search hits. I used it as the starting point to learn the PKPDsim package.  You are right that in the detailed documentation it is already updated.

**Comment by ronkeizer** [comment]
OK, thanks. Will take the old one offline, I thought I already did.

**Comment by Sibojang9** [comment]
I think there might be a typo  at http://pkpdsim.ronkeizer.com/getting-started.html.
The raw HTML code displays at the end of first paragraph.

looks like that from my side : ****<% code("bash") do %>**** library(devtools) install_github("ronkeizer/PKPDsim") library(PKPDsim) **<% end %>**

**Comment by Sibojang9** [comment]
A bug: The DBI package is not automatically installed. It has to be installed manually. 

![snap66](https://cloud.githubusercontent.com/assets/11802171/21327241/254eaa50-c5fc-11e6-893e-8e3d37e53c63.jpg)

**Comment by Sibojang9** [comment]
In the PKPD example at http://pkpdsim.ronkeizer.com/example-pkpd-model.html , I got this error.

![snap70](https://cloud.githubusercontent.com/assets/11802171/21327587/e806a164-c5fd-11e6-808a-537f8cd482ef.jpg)

**Comment by Sibojang9** [comment]
In the shiny example  at http://pkpdsim.ronkeizer.com/example-shiny-app.html,

Without loading some basic libraries, it would not run.  You may want to add  **library(shiny)
library(deSolve)**  to the head of code.

**Comment by ronkeizer** [comment]
on what OS are you?

**Comment by Sibojang9** [comment]
Windows 7

**Comment by Sibojang9** [comment]
It reads like this,
![snap71](https://cloud.githubusercontent.com/assets/11802171/21328056/0edabef4-c600-11e6-9da6-987067badfb6.jpg)
