### ISSUE TITLE
Omitting scale = "V"  argument cause error

### ISSUE THREAD

**Issue by Sibojang9** [ronkeizer/PKPDsim#24]
Sometimes, we do not need the scaling argument, i.e. only the original amount of drug in the observe compartment is needed.   When I omit the scale argument,  errors pop out.

pk1 <- new_ode_model(code = "
  dAdt[1] = -KA * A[1]
  dAdt[2] = +KA * A[1] -(CL/V) * A[2]
  **",   obs = list(cmt = 2)  )

![snap50](https://cloud.githubusercontent.com/assets/11802171/23328994/961be786-fafc-11e6-9086-5d0b6c7d9c86.jpg)

**

**Comment by ronkeizer** [comment]
you're right, should default to 1. Just implemented fix.
