### ISSUE TITLE
consider branching all shiny-related portions to a separate package

### ISSUE THREAD

**Issue by dpastoor** [ronkeizer/PKPDsim#3]
My 'concern' is two-fold:
- all the dependencies and versions that would be required to run the shiny app must be taken into account - and while it looks super promising
- maintenance: long term, balancing the shiny maintenance with the core simulation functionality may be better served (any managed) by having two separate packages

**Comment by dpastoor** [comment]
oh and I'm not sure, but I would expect that having shiny in here will make getting the package onto CRAN a good bit more work, but am not positive

**Comment by ronkeizer** [comment]
yes, it's mostly out of convenience that its one package now. I'm a fan of modularity too, and my plan is also to eventually to branch off the shiny part to "PKPDsim-shiny" or something. Or make a more general shiny library to do stuff with both PKPDsim and vpc packages, not sure yet.
