### ISSUE TITLE
[Feature request] Template to build a shiny app

### ISSUE THREAD

**Issue by Sibojang9** [ronkeizer/PKPDsim#31]
Since the update of PKPDsimShiny package discontinued, is it possible to provide basic R shiny scripts that users can use as a starting point to build their own shiny app?  For example,  script for a "pk_1cmt_oral" model with sliders for CL and Vd.

Thanks.

**Comment by Anathawa** [comment]
Sorry for budding in here, but I've been looking for the same thing, so I might even be able to assist?
The  PKPDsimShiny package actually works nicely.
My only problem is that when I use the suggested code for creating it, using my actual values for V, Cl and Ka, Ka doesn't follow along to the slider. But I think it only needs a small fix, so, I'll put it as an issue on that repository and we can just sort out a fix. :)

**Comment by Sibojang9** [comment]
Hi Anathawa,  I will be happy to work on that with you.

**Comment by Sibojang9** [comment]
Since the source code of sim_ode_shiny is publicly available, I think that I can use it as a template to make my own shiny app.

**Comment by ronkeizer** [comment]
That could be a start indeed. Also, you could just use any example Shiny app in on-line tutorials as starting point. Just substitute the calculation code in server.R that they provide with a few lines of PKPDsim code and you should be good to go.
