### ISSUE TITLE
start profiling for which portions can best use cpp re-writes

### ISSUE THREAD

**Issue by dpastoor** [ronkeizer/PKPDsim#4]
I'll leave the model implementation to you ;-) but I can start taking a crack at tracking down the areas that take the longest to run and can begin to think about the Cpp transformation. I don't think the ODE portions would actually be sped up particularly much as my understanding is deSolve is mostly fortran under the hood anyway, so it will be the data manipulation portions when you're doing the steps between doses etc that I think will actually be best to target.

**Comment by ronkeizer** [comment]
you're welcome to take a crack at it, but I do already have code lying around for this from a previous project. I just need to dig it up, put it in the package and clean it up a bit. So probably better to wait for that?
In the previous project I did actually saw quite a dramatic improvement with moving the model (and a bit of the surrounding data wrangling) to Cpp. Something like a 20x speedup for a 5-equation ODE model if I remember correctly.

**Comment by dpastoor** [comment]
Yeah - it will be interesting to see where the hold ups are - I definitely would expect at least 10-20x increase in the time related to the data manipulation portions, I just don't know how much time that takes relative to the ODE portion. Though looking at your code, it seems to be a good amount of sub-setting the time intervals etc, so I would think it should definitely be non-trivial.
