### ISSUE TITLE
major performance hit with larger # individuals or small step size?

### ISSUE THREAD

**Issue by dpastoor** [ronkeizer/PKPDsim#5]
Hey Ron,

Would you mind checking to see if your results are mirroring mine:

```
library(ggplot2)
library(PKPDsim)
library(microbenchmark)

p <- list(CL = 1,
          V  = 10)

r1 <- new_regimen(amt = 100,
              times = c(0, 12, 24, 36, 48),
              type = "bolus")

microbenchmark(sim_ode (ode = "pk_1cmt_iv",
                par = p,
                regimen = r1,
                step_size = 0.016,
                t_max = 72),
times = 10L)



sim_ode_1000 <- function() {
  sim_ode (ode = "pk_1cmt_iv",
           par = p,
           n_ind = 1000,
           regimen = r1,
           step_size = 0.25,
           t_max = 72)
}

microbenchmark(sim_ode_1000(), times = 2L)

```

It took for the 1000 ind/0.25 hr step size 280 seconds to run (with the cpp simulation function).  

I wrote a (simple) implementation in julia that matches the profiles of this version (so assume both are accurate) but runs in less than a second.

Just wanted to do a gut check and see if you were getting similar results. If so, I will do a more thorough investigation and see if I can figure out where the biggest bottlenecks see if I would be able to replace them with cpp code.

My hunch it is all the subsetting and binding etc that is going on for each dose input and is causing some 'run-away' memory issues so I'm going to guess that the performance targets should actually be on the data manipulation and management more than the simulation bits. 

Would be good to see if your results mirror mine and its not just an issue with my comp before I get too far ahead of guessing.

Devin

**Comment by ronkeizer** [comment]
hi Devin,
Thanks for checking. The C++ is actually pretty fast. However, I haven't made the C++ implementation the default yet, so what probably happened is that you actually used the old implementation (native R). There is a argument "cpp = TRUE" to ode_sim(), which is still FALSE by default because I wanted to do a bit more checking on accuracy. I've made a few other improvements this afternoon, so should be fairly robust now (but can't claim that it'll work for any model yet). There's also the argument cpp_recompile, once you've compiled the model once, you can set that to FALSE to save a second or two.

When I set cpp=TRUE and cpp_recompile=FALSE, the 1000x simulation test you send me runs in 225ms

```
Unit: milliseconds
           expr      min       lq     mean   median       uq      max neval
 sim_ode_1000() 224.0269 224.0269 233.0345 233.0345 242.0421 242.0421     2
```

It's quite an improvement over the old code :) Although I admit that probably wasn't optimal in many places, it's still impressive how much speed you gain by moving to C++. Good to see it matches Julia.

**Comment by ronkeizer** [comment]
By the way, what I moved to C++ now is the function to simulate out the timecourse for one individual. So the larger loop (looping over the patients) is still in R. Theoretically that "patient loop" could also be moved to C++ but I actually expect the improvement gain from that will be fairly negligible, while it will take quite a bit of effort. So I'll probably keep the structure as it is now.

**Comment by dpastoor** [comment]
whew glad to know that I was taking crazy pills, aka not actually reading the source code fully. It's still been pretty amazing how much performance you get with so little work with julia. Of course, can't beat being able to just call everything directly from R. 

Agree that the patient loop unless people are asking to sim 1000's of patients likely wouldn't be a bottleneck.

Nice work!

**Comment by ronkeizer** [comment]
Thanks, also for the benchmark script. I just compared speeds with mlxR too (https://github.com/cran/mlxR), and PKPDsim seems to be about 50% faster :) Need to do a few more checks to see if comparison is completely fair, but it's a good sign.

**Comment by dpastoor** [comment]
Yeah it is super fast with the cpp - btw, do you know what kind of step size monolix/nonmem/lsoda use. I think @vjd mentioned around 10^-6 units.  I tested that step size vs something like 0.1 units and its still lightning fast regardless, but it is about a 10x difference (300 vs 30 ms).  

Can there be issues with precision with using larger step sizes? I also ask because it would seem logical to be able to control the step size separately from the 'sampling times' returned? I'm trying to get my head more wrapped around the more technical portions of ODE's so pardon if this is a silly question.

**Comment by ronkeizer** [comment]
Absolutely, step size != output times, although that is in fact how it is currently implemented for the cpp function. Will update that when I get the chance. That's also why I was saying it is probably not fair at the moment to compare with mlxR. Just need to do some experiments to get a good tradeoff between speed and precision for the default setting. However, I've never found step size very relevant anyhow for the problems we deal with, any reasonably small step size will usually do fine. Perhaps when you shoot a rocket to the moon you want to go to 1e-6 or higher...
