### ISSUE TITLE
Problem installing PKPDsim package in R

### ISSUE THREAD

**Issue by srm54** [ronkeizer/PKPDsim#9]
Hi Ron,

I've been trying to install the PKPDsim package in R and have been having a lot of trouble. The command keeps failing and I'm not sure why:

> library(devtools)
> install_github("ronkeizer/PKPDsim")
> Downloading github repo ronkeizer/PKPDsim@master
> Installing PKPDsim
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
>   --no-environ --no-save --no-restore CMD INSTALL  \
>   '/private/var/folders/f0/p8nbk2m95qv7pz3v72cy3k8c0000gn/T/Rtmpxf3dSk/devtools26e66353d01/ronkeizer-PKPDsim-0cf0304'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
>   --install-tests 
- installing _source_ package ‘PKPDsim’ ...
  *\* R
  *\* exec
  *\* inst
  *\* preparing package for lazy loading
  Warning: replacing previous import by ‘dplyr::select’ when loading ‘PKPDsim’
  Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘inline’
  ERROR: lazy loading failed for package ‘PKPDsim’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/PKPDsim’
  Error: Command failed (1)

Thanks for your help.
Sophia

**Comment by ronkeizer** [comment]
Hi Sophia,
R seems to complain that the "inline" library is not available. Can you try and install that manually before you install PKPDsim?
Ron

**Comment by srm54** [comment]
Yes! Thank you! That did the trick.

**Comment by mct941** [comment]
Hi Ron,
I tried to install this package, but running into slight different issue.  It seems to be looking for Rcpp, even though it is already loaded.  Please see below.

-Max

**library("Rcpp", lib.loc="c:/Rlibs")**
**install_github("ronkeizer/PKPDsim")**
Downloading GitHub repo ronkeizer/PKPDsim@master
from URL https://api.github.com/repos/ronkeizer/PKPDsim/zipball/master
Installing PKPDsim
"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/mtsai/AppData/Local/Temp/RtmpEPGuMY/devtools1bcc58504204/ronkeizer-PKPDsim-3d163f1"  \
  --library="c:/Rlibs" --install-tests 
- installing _source_ package 'PKPDsim' ...
  *\* R
  *\* data
  **\* moving datasets to lazyload DB
  *\* exec
  *\* inst
  *\* tests
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
  **\* arch - i386
  Error in library.dynam(lib, package, package.lib) : 
  DLL 'Rcpp' not found: maybe not installed for this architecture?
  Error: loading failed
  Execution halted
  **\* arch - x64
  ERROR: loading failed for 'i386'
- removing 'c:/Rlibs/PKPDsim'
  Error: Command failed (1)
  >

**Comment by ronkeizer** [comment]
thanks for the issue report. I actually haven't tried installing on Windows, so hard to provide advice here. This week I'm at a conference so don't have access to Windows PC, but will try to reproduce this next week, and let you know what I find. A general advice for such errors is sometimes to upgrade to the latest version of R and to the latest version of all packages, not sure if that could help your problem?

**Comment by dpastoor** [comment]
@mct941 One other test you can try is install another github-based package from source to check that Rtools and compilation through Rcpp are behaving properly. My go-to is devtools::install_github("hadley/dplyr") as it is so heavily involved with Cpp. If that also doesn't install issue is more general and likely unrelated to PKPDsim directly.

That error seems to suggest you have an Rcpp version compiled on a different platform than you are currently using. Where did you get it from and what version is it?

Run the commands and show this output, it could help

```
library(Rcpp)
devtools::session_info()
```

**Comment by nskoch** [comment]
Hi Ron, 

trying a basic example 
> pk1 <- new_ode_model("pk_1cmt_oral")
and I have this error message:

Error in Rcpp::sourceCpp(code = sim_func, rebuild = TRUE, env = globalenv(),  : 
  Error 1 occurred building shared library.

If you have any idea of what's going wrong, I will appreciate.
Best regards
Nicolas

For information I type session_info()
- Session info ----------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       Europe/Paris                
 date     2020-10-13                  

- Packages --------------------------------------------------------------------------
 ! package     * version  date       lib source                            
   assertthat    0.2.1    2019-03-21 [1] CRAN (R 4.0.0)                    
   backports     1.1.10   2020-09-15 [1] CRAN (R 4.0.2)                    
   BH            1.72.0-3 2020-01-08 [1] CRAN (R 4.0.0)                    
   callr         3.5.1    2020-10-13 [1] CRAN (R 4.0.1)                    
 V cli           2.0.2    2020-10-12 [1] CRAN (R 4.0.1)                    
   crayon        1.3.4    2017-09-16 [1] CRAN (R 4.0.0)                    
   curl          4.3      2019-12-02 [1] CRAN (R 4.0.0)                    
   desc          1.2.0    2018-05-01 [1] CRAN (R 4.0.0)                    
   devtools    * 2.3.2    2020-09-18 [1] CRAN (R 4.0.2)                    
   digest        0.6.25   2020-02-23 [1] CRAN (R 4.0.0)                    
   ellipsis      0.3.1    2020-05-15 [1] CRAN (R 4.0.0)                    
   fansi         0.4.1    2020-01-08 [1] CRAN (R 4.0.0)                    
   fs            1.5.0    2020-07-31 [1] CRAN (R 4.0.2)                    
   generics      0.0.2    2018-11-29 [1] CRAN (R 4.0.0)                    
   glue          1.4.2    2020-08-27 [1] CRAN (R 4.0.2)                    
   lubridate     1.7.9    2020-06-08 [1] CRAN (R 4.0.0)                    
   magrittr      1.5      2014-11-22 [1] CRAN (R 4.0.0)                    
   memoise       1.1.0    2017-04-21 [1] CRAN (R 4.0.2)                    
   pkgbuild      1.1.0    2020-07-13 [1] CRAN (R 4.0.2)                    
   pkgload       1.1.0    2020-05-29 [1] CRAN (R 4.0.0)                    
   PKPDsim     * 1.0.1    2020-10-13 [1] Github (ronkeizer/PKPDsim@2a75903)
   prettyunits   1.1.1    2020-01-24 [1] CRAN (R 4.0.0)                    
   processx      3.4.4    2020-09-03 [1] CRAN (R 4.0.2)                    
   ps            1.4.0    2020-10-07 [1] CRAN (R 4.0.2)                    
   R6            2.4.1    2019-11-12 [1] CRAN (R 4.0.0)                    
   Rcpp        * 1.0.5    2020-07-06 [1] CRAN (R 4.0.2)                    
   remotes       2.2.0    2020-07-21 [1] CRAN (R 4.0.2)                    
   rlang         0.4.8    2020-10-08 [1] CRAN (R 4.0.1)                    
   rprojroot     1.3-2    2018-01-03 [1] CRAN (R 4.0.0)                    
   rstudioapi    0.11     2020-02-07 [1] CRAN (R 4.0.0)                    
   sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 4.0.2)                    
   testthat      2.3.2    2020-03-02 [1] CRAN (R 4.0.0)                    
   usethis     * 1.6.3    2020-09-17 [1] CRAN (R 4.0.2)                    
   withr         2.3.0    2020-09-22 [1] CRAN (R 4.0.2)                    

[1] C:/Users/nicol/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.1/library

 V -- Loaded and on-disk version mismatch.
